### ISSUE TITLE
Drawer Component Broken

### ISSUE THREAD

**Issue by RicardoVaranda** [swimlane/ngx-ui#64] opened 2017-06-15 10:14 UTC
ng -v: 
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.0-beta.0
node: 6.10.3
os: darwin x64
@angular/animations: 4.2.2
@angular/common: 4.2.2
@angular/compiler: 4.2.2
@angular/core: 4.2.2
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.2.2
@angular/http: 4.2.2
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.2.2
@angular/platform-browser-dynamic: 4.2.2
@angular/router: 4.2.2
@angular/cli: 1.2.0-beta.0
@angular/language-service: 4.2.2
```

Same code as the example here:
https://swimlane.github.io/ngx-ui/#drawer

Stack:
```
RROR Error: Unable to resolve animation metadata node #undefined
    at visitAnimationNode (browser.es5.js:833)
    at AnimationAstBuilderVisitor.webpackJsonp.../../../animations/@angular/animations/browser.es5.js.AnimationAstBuilderVisitor.build (browser.es5.js:952)
    at buildAnimationAst (browser.es5.js:934)
    at InjectableAnimationEngine.webpackJsonp.../../../animations/@angular/animations/browser.es5.js.AnimationEngine.registerTrigger (browser.es5.js:4495)
    at animations.es5.js:243
    at Array.forEach (<anonymous>)
    at AnimationRendererFactory.webpackJsonp.../../../platform-browser/@angular/platform-browser/animations.es5.js.AnimationRendererFactory.createRenderer (animations.es5.js:243)
    at DebugRendererFactory2.webpackJsonp.../../../core/@angular/core.es5.js.DebugRendererFactory2.createRenderer (core.es5.js:13567)
    at createComponentView (core.es5.js:12171)
    at callWithDebugContext (core.es5.js:13535)
View_DrawerComponent_Host_0 @ DrawerComponent_Host.html:1
proxyClass @ compiler.es5.js:14962
webpackJsonp.../../../core/@angular/core.es5.js.DebugContext_.logError @ core.es5.js:13475
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080
(anonymous) @ core.es5.js:9303
(anonymous) @ platform-browser.es5.js:2668
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:424
onInvokeTask @ core.es5.js:3924
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:191
ZoneTask.invoke @ zone.js:486
DrawerComponent_Host.html:1 ERROR CONTEXT DebugContext_ {view: Object, nodeIndex: 0, nodeDef: Object, elDef: Object, elView: Object}
```

Problem:
Once I click to open the drawer I get the following stacktrace

**Comment by amcdnl** [comment] 2017-06-15 13:15
Yup, seeing this too in latest Angular. On my list this week.

**Comment by RicardoVaranda** [comment] 2017-06-15 13:32
I'll be happy to submit a PR if you point me in the right direction :)

**Comment by amcdnl** [comment] 2017-06-15 15:40
I'm not sure what the issue is atm

**Comment by RicardoVaranda** [comment] 2017-06-16 07:20
@matsko Any chance you could give us some insight on what the issue might be here?

**Comment by amcdnl** [comment] 2017-06-16 13:19
Fixed in latest

**Closed by amcdnl** 2017-06-16 13:19 UTC

**Comment by matsko** [comment] 2017-06-16 20:19
Good to hear that it got fixed in Angular. Sorry guys this bug showed up.
