### ISSUE TITLE
calendar.component.scss not found AOT

### ISSUE THREAD

**Issue by efstathiosntonas** [swimlane/ngx-ui#55] opened 2017-05-24 09:22 UTC
I try to build with angular-cli using --prod --aot and i get the following error:
``` 
ENOENT: no such file or directory, open 'C:\Users\Stathis\WebstormProjects\xxxxx\node_modules\@swimlane\ngx-ui\release\components\calenda
r\calendar.component.scss' 
```
I can't find this scss file.

webpack throws this error:

```
ERROR in Expected 'styles' to be an array of strings.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/client/app.module.ngfactory' in 'C:\Users\Stathis\WebstormProjects\xxxxx\src'
 @ ./src/main.ts 5:0-81
 @ multi ./src/main.ts
```
If I run in development mode there is no error.

What am I missing here?

**Comment by RicardoVaranda** [comment] 2017-05-25 09:00
The issue is caused due to this line:

https://github.com/swimlane/ngx-ui/blob/master/release/components/calendar/calendar.component.js#L92

I'll submit a PR to fix it.

**Comment by efstathiosntonas** [comment] 2017-05-25 09:57
If i remove the line the error goes away but the 'expected styles to be an array' remains

**Comment by farhatmo** [comment] 2017-05-30 13:49
+1

**Comment by RicardoVaranda** [comment] 2017-06-28 13:36
Is there any timeline as to when this will be fixed, currently a blocking task in our project if we intend to use ngx-ui.

**Comment by amcdnl** [comment] 2017-06-29 13:15
@RicardoVaranda - im not sure why this would be the only one having issues.

If you are importing the date picker, you get the calendar. If you import the global module, you get them all.

**Comment by RicardoVaranda** [comment] 2017-06-29 13:55
This is just the first error it returns but like mentioned by @efstathiosntonas even after fixing this specific issue then you start getting all of the errors for the rest of the components. I guess angular compiler just spits out the first error it finds rather than concatenate all of them together. 

I'm not familiar with the steps required in order to turn a component library AOT friendly but will gladly contribute towards making this library if you can point out what needs to be done.

**Comment by amcdnl** [comment] 2017-06-29 17:24
I wonder if we need to do what we did on charts/table with manipulating the scss to css.

https://github.com/swimlane/ngx-charts/blob/master/package.json#L37

**Comment by amcdnl** [comment] 2017-07-07 16:44
Should be fixed in latest.

**Closed by amcdnl** 2017-07-07 16:44 UTC
